### ISSUE TITLE
AttributeError: module 'mxnet.contrib.symbol' has no attribute 'YoloOutput'

### ISSUE THREAD

**Issue by Baozhang-Ren** [zhreshold/mxnet-yolo#32]
Got _AttributeError: module 'mxnet.contrib.symbol' has no attribute 'YoloOutput'_ when trying to run the demo.

**Comment by DavoFranco** [comment]
I am having the same issue.....

**Comment by zhreshold** [comment]
same as #34

**Comment by vikash0837** [comment]
Even after building mxnet from source ,i am getting the same error.
AttributeError: module 'mxnet.contrib.symbol' has no attribute 'YoloOutput'

I followed the following link for building the mxnet from source.
http://mxnet.incubator.apache.org/install/index.html

**Comment by vikash0837** [comment]
Hi,
I looked into the file mxnet/python/mxnet/contrib/symbol.py 
There is no function called YoloOutput. But demo.py is redirecting to 
out = mx.contrib.symbol.YoloOutput(data=pred, num_class=num_classes,
        num_anchor=num_anchor, object_grad_scale=5.0, background_grad_scale=1.0,
        coord_grad_scale=1.0, class_grad_scale=1.0, anchors=anchors,
        nms_topk=400, warmup_samples=12800, name='yolo_output')

I checked for  'YoloOutput' in dir(mx.contrib.symbol) 
which returns False only.

**Comment by zhreshold** [comment]
@vikash0837 Checkout the latest master, I forgot to update darknet symbol file in the previous update
It should be called `Yolo2Output`

**Comment by vikash0837** [comment]
@zhreshold  ,I rebuild with latest master. Still after building ,i am not getting the Yolo2Output function.
After build i tried 
import mxnet as mx
'Yolo2Output' in dir(mx.contrib.symbol) which returns False only

**Comment by vikash0837** [comment]
@zhreshold apart from the existing error there is also a bug in your latest changes.
inside symbol/symbol_darknet19_yolo.py
from symbol.symbol_darknet19 import conv_act_layer, stack_neighbor
you can't import stack_neighbor from symbol_darknet19.py as stack_neighbor function is not present in symbol_darknet19 .py
it has to be imported from common.py

**Comment by zhreshold** [comment]
@vikash0837 By latest master I mean the submodule mxnet in master branch, not official incubator-mxnet. Maybe you are mixing different mxnet.
Try 
```
python -c "import mxnet; print(mxnet)"
```
to see where it locates.
Anyways, thanks for spotting the errors.

**Comment by vikash0837** [comment]
@zhreshold Thanks for your prompt reply. I am using submodule mxnet from your git only.
Here is the link . You can correct me if i am wrong.
[https://github.com/zhreshold/mxnet.git](url) 

I couldn't find the module Yolo2Output anywhere in that repository. It is not populating after build as well .
Response of <python -c "import mxnet; print(mxnet)">

> <module 'mxnet' from '/home/ubuntu/yoloDemo/updated-yolo/mxnet/python/mxnet/__init__.pyc'>

**Comment by ssridhar2065** [comment]
@zhreshold, could you please tell me how to resolve this problem. I am still getting this error.
Am I missing something.
