### ISSUE TITLE
How did you change the mxnet framework?

### ISSUE THREAD

**Issue by xhzcyc** [zhreshold/mxnet-yolo#7]
Hi, zhreshold,
Thanks for your contribution to the algorithm.
Could you do some description about your change of mxnet?

**Comment by zhreshold** [comment]
added the following operators:
yolo_output.* to src/operator/contrib
stack_neighbor into src/operator/matrix_op

**Comment by liben2018** [comment]
@zhreshold, thanks for your code!
I can find the files named with yolo_output in contrib:
yolo_output-inl.h
yolo_output.cc
yolo_output.cu
but, can not find matrix_op in src/operator,
have you changed the code after above answer?
Thanks!

**Comment by zhreshold** [comment]
stack_neighbor is no longer required.

**Comment by liben2018** [comment]
@zhreshold, thanks!
