### ISSUE TITLE
Could the code can do real-time job the same like darknet?

### ISSUE THREAD

**Issue by joyivan** [zhreshold/mxnet-yolo#9]
The origin code in C from official web in 'pjreddie.com' did some real-time jobs, like webcam object recognition or the same job in videos . I just want to know whether the author of mxnet-yolo offer the same function in python, if did, how to use . Thanks for author's effort in the mxnet-yolo  :)

**Comment by zhreshold** [comment]
I guess the speed is somewhat similar to darknet, maybe even better.  
I didn't implement a camera version simply because I don't have a camera to test on cloud. 
Anyone interested is welcomed to submit a PR.

**Comment by joyivan** [comment]
@zhreshold Thanks for your reply, and good job for YOLO v2 using python :)

**Comment by zhreshold** [comment]
#13
